from enum import IntEnum


class ErrorCode(IntEnum):
    SOMETHING_WENT_WRONG = 503
    USER_ALREADY_EXISTS = 3000
    USER_NOT_FOUND = 4010
    PHONE_NUMBER_MISMATCH = 4011
    OTP_CHALLENGE_NOT_FOUND = 4012
    OTP_CHALLENGE_IS_WRONG = 4013
    INTERNAL_SERVER_ERROR = 500
